import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  // Option 1: auto-generated from folder structure
  // mysqlSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Option 2: explicit order and labels
  mysqlSidebar: [
    { type: 'doc', id: 'mysql/index', label: 'Overview' },
    {
      type: 'category',
      label: 'Backup',
      items: ['mysql/backup/mysqldump']
    },
    {
      type: 'category',
      label: 'Admin',
      items: [
        'mysql/admin/performance',
        'mysql/admin/drop-tables'
      ]
    },
    { type: 'doc', id: 'mysql/magento', label: 'Magento' },
    {
      type: 'category',
      label: 'Reference',
      items: ['mysql/reference/cheatsheet']
    }
  ]
}

export default sidebars
